format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$status\
$conda\
$shell\
$character
"""

# right_format = "$time"

# [time]
# disabled = false
# style = "bold bright-black"
# format = "[$time]($style)"

# uncomment or set disabled as true for prompt on the same line
[line_break]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[conda]
symbol = "conda "

[cmake]
symbol = "cmake "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[gcloud]
symbol = "gcp "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[java]
symbol = "java "

[julia]
symbol = "jl "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
Fedora = "fed "
FreeBSD = "fbsd "
Linux = "lnx "
Macos = "mac "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Ubuntu = "ubnt "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "
